### ISSUE TITLE
Relative Units

### ISSUE THREAD

**Issue by Shinmera** [Shinmera/LASS#10]
#9 actually broke existing stylesheets by attempting to statically compile `calc`. Specifically the current system does not understand the `vh` and `vw` units, and also attempts to convert other relative units like `em`. This is not acceptable.

When encountering relative units like `vh`, `vw`, `em`, the system *must* accept them blindly and propagate them outwards, potentially producing a `calc` expression if the units cannot be resolved.

**Comment by Shinmera** [comment]
@egao1980 egao1980

**Comment by egao1980** [comment]
Conversion happens only if you mix absolute and relative units. This normally should not happen.

**Comment by Shinmera** [comment]
It *does* happen, though, and sometimes with good reason.

**Comment by egao1980** [comment]
Ok, will fix. Do you have an example?

**Comment by Shinmera** [comment]
This for example cannot be computed AoT:
```
:margin (calc (- 50vh 3em)) (calc (- 50vw 3em))
```

Another example I found in one of my stylesheets is:
```
:right (calc (+ -1.0em 1px))
```

**Comment by egao1980** [comment]
Thanks. So, we treat em/en as incompatible with px. And vh/vw - as incompatible with any of them?

**Comment by Shinmera** [comment]
Well, `em` should only be compatible with itself, same for `vh` and `vw`. Since their actual size is end-user specific we can't do anything with them except output them verbatim.

**Comment by egao1980** [comment]
I'm still working on the proper fix. There's a workaround using raw strings - (values "calc(50vh - 3em)").

**Comment by l0rdn1bbl3r** [comment]
Hi,

since this affected my own code and seems still unfixed I tried to fix it. 

It seems to me that not only `vh, vw` and `em` are affected but all the relative css units. 
(I.e. `em, ex, ch, rem, lh, vw, vh, vmin` and `vmax`).

Defining all of these in `units.lisp` without a `:def` arg, almost automatically takes care of not mixing them since a condition of type `pq:invalid-unit-conversion-error` is signaled. It could be handled in the respective `css-op`, like this:

``` common-lisp
(defmacro define-css-op (op)
  `(define-property-function ,(string op) (&rest args)
     (handler-case (with-css-units
                     (css-number-string
                      (apply #',(intern (string-upcase (concatenate 'string "q" (string op))))
                             (mapcar (lambda (x) (parse-css-number (resolve x))) args))))
       ;; Catch errors that originate from non-convertable (e.g. px and em) units.
       (pq:invalid-unit-conversion-error ()
         (format nil ,(format nil "(~~{~~a~~^ ~a ~~})" op) (mapcar #'resolve args))))))
```
This works fine on non-nested expression like 

``` common-lisp
 '(.foo :margin (calc (- 50vh 3em)))
```
Output:
``` css
.foo{ margin: calc((50vh - 3em)); }
```
But when the calc expression is nested this doesn't work
``` common-lisp
(compile-and-write
 '(.foo :margin (calc (- (+ 50vmin 5em) (- 30px 10rem)))))
```
An `invalid-array-index-error` is signaled because `parse-css-number` does not consider the case that its input isn't a float at all.
But is it called with resolved strings like "(50vmin + 5em)".

`parse-css-number` could check this and signal an appropriate condition

``` common-lisp
(defun parse-css-number (x &key unit)
  (cond ((stringp x)
         (multiple-value-bind (val idx) (parse-float x :junk-allowed t)
           (when (zerop idx)
             (signal 'pq:invalid-unit-error))
         ;; omitted for brevity
         ...     
        ))
```
Then in the css-op we can simply handle `pq:invalid-unit-error`.

Now somthing like 
```common-lisp
(compile-and-write
 '(.foo :margin (calc (- (+ 50vmin 5em) (- 30px (- 5rem 10rem))))))
```
results in 
``` css
.foo{ margin: calc(((50vmin + 5em) - (30px - -5.00rem))); }
```

I might be debatable whether more elegant solutions exist. But I found it to be quickest while not being familiar with the code. 

I also realized that with the code currently in master something like `'(.foo :margin (calc (- 50px 10px)))` results in the faulty `.foo{ margin: calc40.00px; }`. The `calc` property function doesn't emit parens when it spots another property function as `car` of its arg. But either calc has to do it or the respective property function.

I implemented these fixes and tried them with most combinations of units that came to my mind. I haven't written any tests for it, though. I can submit a pull request if you like.

**Comment by egao1980** [comment]
Thanks a lot! Please send a pull request. I've attempted to fix this but got stuck and finding it hard to find free time :( will be happy to test manually and add some tests.

**Comment by l0rdn1bbl3r** [comment]
Hi,

I will send a pull request asap (this week).

-------- Original Message --------
